# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'regressionApp2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication
from matplotlib.backends.backend_qt5agg import (NavigationToolbar2QT as NavigationToolbar)

# UI Code generated using QtDesigner
class Ui_RegressionApp(object):
    def setupUi(self, RegressionApp):
        RegressionApp.setObjectName("RegressionApp")
        RegressionApp.resize(661, 437)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RegressionApp.sizePolicy().hasHeightForWidth())
        RegressionApp.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(RegressionApp)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.predictorsTextBox = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predictorsTextBox.sizePolicy().hasHeightForWidth())
        self.predictorsTextBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.predictorsTextBox.setFont(font)
        self.predictorsTextBox.setObjectName("predictorsTextBox")
        self.verticalLayout_4.addWidget(self.predictorsTextBox)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 2, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.categoricalTextBox = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.categoricalTextBox.sizePolicy().hasHeightForWidth())
        self.categoricalTextBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.categoricalTextBox.setFont(font)
        self.categoricalTextBox.setObjectName("categoricalTextBox")
        self.verticalLayout_5.addWidget(self.categoricalTextBox)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 3, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.responseTextBox = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.responseTextBox.sizePolicy().hasHeightForWidth())
        self.responseTextBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.responseTextBox.setFont(font)
        self.responseTextBox.setObjectName("responseTextBox")
        self.verticalLayout_3.addWidget(self.responseTextBox)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.categoricalLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.categoricalLabel.sizePolicy().hasHeightForWidth())
        self.categoricalLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.categoricalLabel.setFont(font)
        self.categoricalLabel.setObjectName("categoricalLabel")
        self.horizontalLayout_8.addWidget(self.categoricalLabel)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.responseLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.responseLabel.sizePolicy().hasHeightForWidth())
        self.responseLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.responseLabel.setFont(font)
        self.responseLabel.setObjectName("responseLabel")
        self.horizontalLayout_3.addWidget(self.responseLabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.predictorsLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predictorsLabel.sizePolicy().hasHeightForWidth())
        self.predictorsLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.predictorsLabel.setFont(font)
        self.predictorsLabel.setObjectName("predictorsLabel")
        self.horizontalLayout_7.addWidget(self.predictorsLabel)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 8, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.statisticsLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.statisticsLabel.setFont(font)
        self.statisticsLabel.setObjectName("statisticsLabel")
        self.verticalLayout.addWidget(self.statisticsLabel)
        self.statisticsTextBox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.statisticsTextBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.statisticsTextBox.setFont(font)
        self.statisticsTextBox.setReadOnly(True)
        self.statisticsTextBox.setPlainText("")
        self.statisticsTextBox.setObjectName("statisticsTextBox")
        self.verticalLayout.addWidget(self.statisticsTextBox)
        spacerItem6 = QtWidgets.QSpacerItem(20, 9, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem6)
        self.gridLayout_3.addLayout(self.verticalLayout, 10, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem7)
        self.regressionPlot = MplWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regressionPlot.sizePolicy().hasHeightForWidth())
        self.regressionPlot.setSizePolicy(sizePolicy)
        self.regressionPlot.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.regressionPlot.setAcceptDrops(True)
        self.regressionPlot.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.regressionPlot.setObjectName("regressionPlot")
        self.verticalLayout_2.addWidget(self.regressionPlot)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 10, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.loaderLabel = QtWidgets.QLabel(self.centralwidget)
        self.loaderLabel.setText("")
        self.loaderLabel.setObjectName("loaderLabel")
        self.horizontalLayout.addWidget(self.loaderLabel)
        self.runRegressionButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runRegressionButton.sizePolicy().hasHeightForWidth())
        self.runRegressionButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.runRegressionButton.setFont(font)
        self.runRegressionButton.setObjectName("runRegressionButton")
        self.horizontalLayout.addWidget(self.runRegressionButton)
        self.gridLayout_3.addLayout(self.horizontalLayout, 9, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem9, 5, 0, 1, 1)
        self.title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(24)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.gridLayout_3.addWidget(self.title, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5)
        self.typeComboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeComboBox.sizePolicy().hasHeightForWidth())
        self.typeComboBox.setSizePolicy(sizePolicy)
        self.typeComboBox.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.typeComboBox.setFont(font)
        self.typeComboBox.setObjectName("typeComboBox")
        self.typeComboBox.addItem("")
        self.typeComboBox.setItemText(0, "")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.verticalLayout_10.addWidget(self.typeComboBox)
        self.gridLayout.addLayout(self.verticalLayout_10, 0, 2, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.inputFileLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputFileLabel.sizePolicy().hasHeightForWidth())
        self.inputFileLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputFileLabel.setFont(font)
        self.inputFileLabel.setObjectName("inputFileLabel")
        self.verticalLayout_11.addWidget(self.inputFileLabel)
        self.gridLayout.addLayout(self.verticalLayout_11, 1, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem10 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_9.addItem(spacerItem10)
        self.typeLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeLabel.sizePolicy().hasHeightForWidth())
        self.typeLabel.setSizePolicy(sizePolicy)
        self.typeLabel.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.typeLabel.setFont(font)
        self.typeLabel.setObjectName("typeLabel")
        self.verticalLayout_9.addWidget(self.typeLabel)
        self.gridLayout.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem11 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem11)
        self.inputFileTextBox = QtWidgets.QLineEdit(self.centralwidget)
        self.inputFileTextBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputFileTextBox.sizePolicy().hasHeightForWidth())
        self.inputFileTextBox.setSizePolicy(sizePolicy)
        self.inputFileTextBox.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputFileTextBox.setFont(font)
        self.inputFileTextBox.setReadOnly(True)
        self.inputFileTextBox.setPlaceholderText("")
        self.inputFileTextBox.setObjectName("inputFileTextBox")
        self.verticalLayout_12.addWidget(self.inputFileTextBox)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_12.addWidget(self.label_6)
        self.gridLayout.addLayout(self.verticalLayout_12, 1, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.standardizeCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.standardizeCheckBox.sizePolicy().hasHeightForWidth())
        self.standardizeCheckBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.standardizeCheckBox.setFont(font)
        self.standardizeCheckBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.standardizeCheckBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.standardizeCheckBox.setObjectName("standardizeCheckBox")
        self.horizontalLayout_2.addWidget(self.standardizeCheckBox)
        spacerItem12 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.degreeLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.degreeLabel.sizePolicy().hasHeightForWidth())
        self.degreeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.degreeLabel.setFont(font)
        self.degreeLabel.setObjectName("degreeLabel")
        self.horizontalLayout_2.addWidget(self.degreeLabel)
        self.degreeTextBox = QtWidgets.QLineEdit(self.centralwidget)
        self.degreeTextBox.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.degreeTextBox.setFont(font)
        self.degreeTextBox.setObjectName("degreeTextBox")
        self.horizontalLayout_2.addWidget(self.degreeTextBox)
        self.alphaLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alphaLabel.sizePolicy().hasHeightForWidth())
        self.alphaLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.alphaLabel.setFont(font)
        self.alphaLabel.setObjectName("alphaLabel")
        self.horizontalLayout_2.addWidget(self.alphaLabel)
        self.alphaTextBox = QtWidgets.QLineEdit(self.centralwidget)
        self.alphaTextBox.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.alphaTextBox.setFont(font)
        self.alphaTextBox.setObjectName("alphaTextBox")
        self.horizontalLayout_2.addWidget(self.alphaTextBox)
        spacerItem13 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem14)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 3)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseButton.sizePolicy().hasHeightForWidth())
        self.browseButton.setSizePolicy(sizePolicy)
        self.browseButton.setMaximumSize(QtCore.QSize(55, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browseButton.setFont(font)
        self.browseButton.setObjectName("browseButton")
        self.verticalLayout_13.addWidget(self.browseButton)
        self.gridLayout.addLayout(self.verticalLayout_13, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(8)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 4, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 8, 0, 1, 1)
        RegressionApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RegressionApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 661, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        RegressionApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RegressionApp)
        self.statusbar.setObjectName("statusbar")
        RegressionApp.setStatusBar(self.statusbar)
        self.actionSave_Graph = QtWidgets.QAction(RegressionApp)
        self.actionSave_Graph.setObjectName("actionSave_Graph")
        self.actionSave_Statistics = QtWidgets.QAction(RegressionApp)
        self.actionSave_Statistics.setObjectName("actionSave_Statistics")
        self.actionClear_All = QtWidgets.QAction(RegressionApp)
        self.actionClear_All.setObjectName("actionClear_All")
        self.actionExit = QtWidgets.QAction(RegressionApp)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionSave_Graph)
        self.menuFile.addAction(self.actionSave_Statistics)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClear_All)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        
        ## Code for interactive UI
        self.browseButton.clicked.connect(self.browse)
        self.browseButton.setAutoDefault(True)
        self.typeComboBox.currentTextChanged.connect(self.on_combobox_changed)
        self.runRegressionButton.clicked.connect(self.run_regression)
        self.runRegressionButton.setAutoDefault(True)
        self.degreeLabel.hide()
        self.degreeTextBox.hide()
        self.alphaLabel.hide()
        self.alphaTextBox.hide()
        absPath = QtCore.QDir.currentPath()
        self.movie = QtGui.QMovie(absPath + "/imageformats/ajax-loader.gif")
        self.loaderLabel.setMovie(self.movie)
        RegressionApp.setWindowIcon(QtGui.QIcon("piechart.png"))
        RegressionApp.addToolBar(NavigationToolbar(self.regressionPlot.canvas, self.regressionPlot))

        ## Code for menu bar
        self.actionClear_All.triggered.connect(self.clear_all)
        self.actionExit.triggered.connect(self.exit_app)
        self.actionSave_Graph.triggered.connect(self.save_graph)
        self.actionSave_Statistics.triggered.connect(self.save_statistics)

        self.retranslateUi(RegressionApp)
        QtCore.QMetaObject.connectSlotsByName(RegressionApp)
        RegressionApp.setTabOrder(self.typeComboBox, self.inputFileTextBox)
        RegressionApp.setTabOrder(self.inputFileTextBox, self.browseButton)
        RegressionApp.setTabOrder(self.browseButton, self.degreeTextBox)
        RegressionApp.setTabOrder(self.degreeTextBox, self.alphaTextBox)
        RegressionApp.setTabOrder(self.alphaTextBox, self.responseTextBox)
        RegressionApp.setTabOrder(self.responseTextBox, self.predictorsTextBox)
        RegressionApp.setTabOrder(self.predictorsTextBox, self.categoricalTextBox)
        RegressionApp.setTabOrder(self.categoricalTextBox, self.runRegressionButton)
        RegressionApp.setTabOrder(self.runRegressionButton, self.statisticsTextBox)
        RegressionApp.setTabOrder(self.statisticsTextBox, self.regressionPlot)

    ## Code generated from QtDesigner
    def retranslateUi(self, RegressionApp):
        _translate = QtCore.QCoreApplication.translate
        RegressionApp.setWindowTitle(_translate("RegressionApp", "Regression Application"))
        self.label_2.setText(_translate("RegressionApp", "*Comma delimited (size, weight, age)"))
        self.label_3.setText(_translate("RegressionApp", "*Comma delimited (model, month, sex)"))
        self.label.setText(_translate("RegressionApp", "*Only one response variable"))
        self.categoricalLabel.setText(_translate("RegressionApp", "Categorical Variables:"))
        self.responseLabel.setText(_translate("RegressionApp", "*Response:"))
        self.predictorsLabel.setText(_translate("RegressionApp", "*Predictors:"))
        self.statisticsLabel.setText(_translate("RegressionApp", "Statistics"))
        self.runRegressionButton.setText(_translate("RegressionApp", "Run"))
        self.title.setText(_translate("RegressionApp", "Perform a Regression!"))
        self.label_5.setText(_translate("RegressionApp", "Choose regression type:"))
        self.typeComboBox.setItemText(1, _translate("RegressionApp", "Linear Regression"))
        self.typeComboBox.setItemText(2, _translate("RegressionApp", "Logistic Regression"))
        self.typeComboBox.setItemText(3, _translate("RegressionApp", "Polynomial Regression"))
        self.typeComboBox.setItemText(4, _translate("RegressionApp", "Ridge Regression"))
        self.typeComboBox.setItemText(5, _translate("RegressionApp", "Lasso Regression"))
        self.typeComboBox.setItemText(6, _translate("RegressionApp", "ElasticNet Regression"))
        self.inputFileLabel.setText(_translate("RegressionApp", "*Input File:"))
        self.typeLabel.setText(_translate("RegressionApp", "*Type:"))
        self.label_6.setText(_translate("RegressionApp", "*.csv or .xlsx file"))
        self.standardizeCheckBox.setText(_translate("RegressionApp", "Standardize:"))
        self.degreeLabel.setText(_translate("RegressionApp", "*Degree:"))
        self.alphaLabel.setText(_translate("RegressionApp", "*Alpha:"))
        self.browseButton.setText(_translate("RegressionApp", "Browse"))
        self.label_4.setText(_translate("RegressionApp", "*Required"))
        self.menuFile.setTitle(_translate("RegressionApp", "File"))
        self.actionSave_Graph.setText(_translate("RegressionApp", "Save Graph"))
        self.actionSave_Graph.setShortcut(_translate("RegressionApp", "Ctrl+G"))
        self.actionSave_Statistics.setText(_translate("RegressionApp", "Save Statistics"))
        self.actionSave_Statistics.setShortcut(_translate("RegressionApp", "Ctrl+S"))
        self.actionClear_All.setText(_translate("RegressionApp", "Clear All"))
        self.actionClear_All.setShortcut(_translate("RegressionApp", "Ctrl+K"))
        self.actionExit.setText(_translate("RegressionApp", "Exit"))
        self.actionExit.setShortcut(_translate("RegressionApp", "Esc"))

    ## Executed when browse button is clicked
    def browse(self):
        fileName, _ = QtWidgets.QFileDialog.getOpenFileName(None, "Browse", "", "CSV Files (*.csv);;Excel Files (*.xlsx)")
        self.inputFileTextBox.setText(fileName)
        
    ## Show degree and alpha text box depending on what type of regression
    ## user selects
    def on_combobox_changed(self):
        if self.typeComboBox.currentText() == "Polynomial Regression":
            self.degreeLabel.show()
            self.degreeTextBox.show()
            self.alphaLabel.hide()
            self.alphaTextBox.hide()
        elif self.typeComboBox.currentText() == "ElasticNet Regression":
            self.degreeLabel.hide()
            self.degreeTextBox.hide()
            self.alphaLabel.show()
            self.alphaTextBox.show()
        else:
            self.degreeLabel.hide()
            self.degreeTextBox.hide()
            self.alphaLabel.hide()
            self.alphaTextBox.hide()
       
    ## Restores form to initial state
    def clear_all(self):
        index = self.typeComboBox.findText("")
        self.typeComboBox.setCurrentIndex(index)
        self.inputFileTextBox.setText("")
        self.standardizeCheckBox.setChecked(False)
        self.degreeTextBox.setText("")
        self.alphaTextBox.setText("")
        self.responseTextBox.setText("")
        self.predictorsTextBox.setText("")
        self.categoricalTextBox.setText("")
        self.statisticsTextBox.setPlainText("")
        self.regressionPlot.canvas.axes.clear()
        self.regressionPlot.canvas.draw()
        
    ## Closes application
    def exit_app(self):
        sys.exit()
        
    ## Opens file explorer for user to save graph as a png file
    def save_graph(self):
        filePath, _ = QtWidgets.QFileDialog.getSaveFileName(None, "Save Image", "", "PNG File (*.png);;PDF File (*.pdf)")
        self.regressionPlot.canvas.figure.savefig(filePath)
        
    ## Opens file explorer for user to save statistics as a txt file
    def save_statistics(self):
        filePath, _ = QtWidgets.QFileDialog.getSaveFileName(None, "Save File", "", "Text File (*.txt);;CSV File (*.csv);;JSON File (*.json)")
        with open(filePath, 'a+') as f:
            f.write(self.statisticsTextBox.toPlainText())
        
    ## Executed when user clicks runRegression button
    def run_regression(self):
        self.loaderLabel.show()
        self.movie.start()
        QApplication.instance().processEvents()
        regressionType = self.typeComboBox.currentText()
        inputFilePath = self.inputFileTextBox.text()
        #standardize is 0 for unchecked and 2 for checked
        standardize = self.standardizeCheckBox.checkState()
        degree = self.degreeTextBox.text()
        alpha = self.alphaTextBox.text()
        responseVariable = self.responseTextBox.text()
        predictors = self.predictorsTextBox.text()
        categoricalVariables = self.categoricalTextBox.text()
        perform_regression(self, regressionType, inputFilePath, standardize,
                           degree, alpha, responseVariable, predictors, 
                           categoricalVariables)
        QApplication.instance().processEvents()
        self.movie.stop()
        self.loaderLabel.hide()
        
from mplwidget import MplWidget
from regression import perform_regression

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle(QtWidgets.QStyleFactory.create('Fusion'))
    RegressionApp = QtWidgets.QMainWindow()
    ui = Ui_RegressionApp()
    ui.setupUi(RegressionApp)
    RegressionApp.showMaximized()
    RegressionApp.show()
    sys.exit(app.exec_())

