# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'regressionApp2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import (NavigationToolbar2QT as NavigationToolbar)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(300, 0, 400, 61))
        font = QtGui.QFont()    
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.regressionPlot = MplWidget(self.centralwidget)
        self.regressionPlot.setGeometry(QtCore.QRect(500, 280, 341, 261))
        self.regressionPlot.setObjectName("regressionPlot")
        self.runRegressionButton = QtWidgets.QPushButton(self.centralwidget)
        self.runRegressionButton.setGeometry(QtCore.QRect(740, 230, 91, 31))
        self.runRegressionButton.setObjectName("runRegressionButton")
        self.statisticsTextBox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.statisticsTextBox.setGeometry(QtCore.QRect(30, 290, 361, 241))
        self.statisticsTextBox.setObjectName("statisticsTextBox")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 80, 481, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.standardizeCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.standardizeCheckBox.setObjectName("standardizeCheckBox")
        self.gridLayout.addWidget(self.standardizeCheckBox, 2, 0, 1, 1)
        self.browseButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseButton.sizePolicy().hasHeightForWidth())
        self.browseButton.setSizePolicy(sizePolicy)
        self.browseButton.setMaximumSize(QtCore.QSize(55, 16777215))
        self.browseButton.setObjectName("browseButton")
        self.gridLayout.addWidget(self.browseButton, 1, 4, 1, 1)
        self.typeLabel = QtWidgets.QLabel(self.layoutWidget)
        self.typeLabel.setObjectName("typeLabel")
        self.gridLayout.addWidget(self.typeLabel, 0, 0, 1, 1)
        self.inputFileLabel = QtWidgets.QLabel(self.layoutWidget)
        self.inputFileLabel.setObjectName("inputFileLabel")
        self.gridLayout.addWidget(self.inputFileLabel, 1, 0, 1, 1)
        self.typeComboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.typeComboBox.setObjectName("typeComboBox")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.gridLayout.addWidget(self.typeComboBox, 0, 2, 1, 3)
        self.inputFileTextBox = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputFileTextBox.setEnabled(True)
        self.inputFileTextBox.setReadOnly(True)
        self.inputFileTextBox.setPlaceholderText("")
        self.inputFileTextBox.setObjectName("inputFileTextBox")
        self.gridLayout.addWidget(self.inputFileTextBox, 1, 2, 1, 1)
        self.multivariateCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.multivariateCheckBox.setObjectName("multivariateCheckBox")
        self.gridLayout.addWidget(self.multivariateCheckBox, 2, 2, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(520, 80, 311, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.categoricalLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.categoricalLabel.setObjectName("categoricalLabel")
        self.gridLayout_2.addWidget(self.categoricalLabel, 3, 0, 1, 1)
        self.responseTextBox = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.responseTextBox.setObjectName("responseTextBox")
        self.gridLayout_2.addWidget(self.responseTextBox, 1, 1, 1, 1)
        self.responseLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.responseLabel.setObjectName("responseLabel")
        self.gridLayout_2.addWidget(self.responseLabel, 1, 0, 1, 1)
        self.categoricalTextBox = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.categoricalTextBox.setObjectName("categoricalTextBox")
        self.gridLayout_2.addWidget(self.categoricalTextBox, 3, 1, 1, 1)
        self.predictorsLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.predictorsLabel.setObjectName("predictorsLabel")
        self.gridLayout_2.addWidget(self.predictorsLabel, 2, 0, 1, 1)
        self.predictorsTextBox = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.predictorsTextBox.setObjectName("predictorsTextBox")
        self.gridLayout_2.addWidget(self.predictorsTextBox, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1099, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClear_All = QtWidgets.QAction(MainWindow)
        self.actionClear_All.setObjectName("actionClear_All")
        self.actionSave_Graph = QtWidgets.QAction(MainWindow)
        self.actionSave_Graph.setObjectName("actionSave_Graph")
        self.actionSave_Statistics = QtWidgets.QAction(MainWindow)
        self.actionSave_Statistics.setObjectName("actionSave_Statistics")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionClear_All_2 = QtWidgets.QAction(MainWindow)
        self.actionClear_All_2.setObjectName("actionClear_All_2")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.menuFile.addAction(self.actionClear_All)
        self.menuFile.addAction(self.actionSave_Graph)
        self.menuFile.addAction(self.actionSave_Statistics)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClear_All_2)
        self.menuFile.addAction(self.actionExit_2)
        self.menubar.addAction(self.menuFile.menuAction())
        
        self.browseButton.clicked.connect(self.browse)
        self.runRegressionButton.clicked.connect(self.run_regression)
        MainWindow.addToolBar(NavigationToolbar(self.regressionPlot.canvas, self.regressionPlot))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.typeComboBox, self.inputFileTextBox)
        MainWindow.setTabOrder(self.inputFileTextBox, self.browseButton)
        MainWindow.setTabOrder(self.browseButton, self.standardizeCheckBox)
        MainWindow.setTabOrder(self.standardizeCheckBox, self.multivariateCheckBox)
        MainWindow.setTabOrder(self.multivariateCheckBox, self.responseTextBox)
        MainWindow.setTabOrder(self.responseTextBox, self.predictorsTextBox)
        MainWindow.setTabOrder(self.predictorsTextBox, self.categoricalTextBox)
        MainWindow.setTabOrder(self.categoricalTextBox, self.runRegressionButton)
        MainWindow.setTabOrder(self.runRegressionButton, self.statisticsTextBox)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Perform a Regression!"))
        self.runRegressionButton.setText(_translate("MainWindow", "Run Regression"))
        self.statisticsTextBox.setPlainText(_translate("MainWindow", "Statistics:"))
        self.standardizeCheckBox.setText(_translate("MainWindow", "Standardize"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.typeLabel.setText(_translate("MainWindow", "Type:"))
        self.inputFileLabel.setText(_translate("MainWindow", "Input File:"))
        self.typeComboBox.setItemText(0, _translate("MainWindow", "Linear Regression"))
        self.typeComboBox.setItemText(1, _translate("MainWindow", "Logistic Regression"))
        self.typeComboBox.setItemText(2, _translate("MainWindow", "Polynomial Regression"))
        self.typeComboBox.setItemText(3, _translate("MainWindow", "Stepwise Regression"))
        self.typeComboBox.setItemText(4, _translate("MainWindow", "Ridge Regression"))
        self.typeComboBox.setItemText(5, _translate("MainWindow", "Lasso Regression"))
        self.typeComboBox.setItemText(6, _translate("MainWindow", "ElasticNet Regression"))
        self.multivariateCheckBox.setText(_translate("MainWindow", "Multivariate"))
        self.categoricalLabel.setText(_translate("MainWindow", "Categorical Variables:"))
        self.responseLabel.setText(_translate("MainWindow", "Response"))
        self.predictorsLabel.setText(_translate("MainWindow", "Predictors"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionClear_All.setText(_translate("MainWindow", "New Regression"))
        self.actionSave_Graph.setText(_translate("MainWindow", "Save Graph"))
        self.actionSave_Statistics.setText(_translate("MainWindow", "Save Statistics"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionClear_All_2.setText(_translate("MainWindow", "Clear All"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        
    def browse(self):
        fileName, _ = QtWidgets.QFileDialog.getOpenFileName(None, "File Explorer", "", "CSV Files (*.csv);;Excel Files (*.xlsx)")
        self.inputFileTextBox.setText(fileName)
        
    def run_regression(self):
        regressionType = self.typeComboBox.currentText()
        inputFilePath = self.inputFileTextBox.text()
        #standardize is 0 for unchecked and 2 for checked
        standardize = self.standardizeCheckBox.checkState()
        multivariate = self.multivariateCheckBox.checkState()
        responseVariable = self.responseTextBox.text()
        predictors = self.predictorsTextBox.text()
        categoricalVariables = self.categoricalTextBox.text()
        perform_regression(self, regressionType, inputFilePath, standardize,
                            multivariate, responseVariable, predictors, categoricalVariables)
        
from mplwidget import MplWidget
from regression import perform_regression

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle(QtWidgets.QStyleFactory.create('Fusion'))
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

